import { useCallback, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import './TradeHubPage.css'

export default function TradeHubPage({ session }) {
  const userId=session.user.id,[profile,setProfile]=useState({display_name:'',discoverable:false}),[matches,setMatches]=useState([]),[threads,setThreads]=useState([]),[active,setActive]=useState(null),[messages,setMessages]=useState([]),[body,setBody]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true)
  const loadThreads=useCallback(async()=>{const {data,error}=await supabase.from('trade_threads').select('*,requested:requested_figure_id(name),offered:offered_figure_id(name)').order('updated_at',{ascending:false});if(error)setNotice(error.message);setThreads(data||[])},[])
  const loadMatches=useCallback(async()=>{const {data,error}=await supabase.rpc('find_trade_matches');if(error)setNotice(error.message);setMatches(data||[])},[])
  useEffect(()=>{Promise.all([supabase.from('trade_profiles').select('*').eq('user_id',userId).maybeSingle(),loadThreads()]).then(([{data}])=>{if(data)setProfile(data);setLoading(false)})},[userId,loadThreads])
  useEffect(()=>{if(profile.discoverable)loadMatches();else setMatches([])},[profile.discoverable,loadMatches])
  const openThread=useCallback(async(thread)=>{setActive(thread);const {data,error}=await supabase.from('trade_messages').select('*').eq('thread_id',thread.id).order('created_at');if(error)setNotice(error.message);setMessages(data||[])},[])
  useEffect(()=>{if(!active)return;const channel=supabase.channel(`trade-${active.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'trade_messages',filter:`thread_id=eq.${active.id}`},({new:row})=>setMessages(old=>old.some(x=>x.id===row.id)?old:[...old,row])).subscribe();return()=>{supabase.removeChannel(channel)}},[active])
  async function saveProfile(e){e.preventDefault();const payload={user_id:userId,display_name:profile.display_name.trim(),discoverable:profile.discoverable,updated_at:new Date().toISOString()},{data,error}=await supabase.from('trade_profiles').upsert(payload).select().single();setNotice(error?error.message:'Trade matching preferences saved.');if(data)setProfile(data)}
  async function start(match){const {data,error}=await supabase.rpc('start_trade_conversation',{p_other:match.other_user_id,p_requested:match.requested_figure_id,p_offered:match.offered_figure_id});if(error)return setNotice(error.message);await loadThreads();const {data:thread}=await supabase.from('trade_threads').select('*,requested:requested_figure_id(name),offered:offered_figure_id(name)').eq('id',data).single();if(thread)openThread(thread)}
  async function send(e){e.preventDefault();if(!body.trim()||!active)return;const text=body.trim();setBody('');const {error}=await supabase.from('trade_messages').insert({thread_id:active.id,sender_id:userId,body:text});if(error){setBody(text);setNotice(error.message)}}
  async function updateStatus(status){const {error}=await supabase.from('trade_threads').update({status,updated_at:new Date().toISOString()}).eq('id',active.id);if(error)return setNotice(error.message);setActive({...active,status});loadThreads()}
  async function block(){const other=active.member_a===userId?active.member_b:active.member_a;const {error}=await supabase.from('trade_blocks').insert({blocker_id:userId,blocked_id:other});if(error)return setNotice(error.message);await updateStatus('closed');setNotice('Member blocked. They can no longer match or message you.')}
  async function report(){const reason=window.prompt('Briefly describe the safety or conduct concern:');if(!reason)return;const other=active.member_a===userId?active.member_b:active.member_a;const {error}=await supabase.from('trade_reports').insert({reporter_id:userId,reported_user_id:other,thread_id:active.id,reason});setNotice(error?error.message:'Report submitted for review.')}
  if(loading)return <div className="center compact">Loading trade matches…</div>
  return <main className="trade-hub"><header className="page-header"><div><span className="eyebrow">Collector-to-collector</span><h1>Trade Matches & Messages</h1><p>Find reciprocal wishlist matches and discuss a trade privately.</p></div></header>{notice&&<p className="form-message trade-notice">{notice}</p>}
    <section className="trade-safety"><strong>Trade safely</strong><span>Keep communication here, verify photos and condition, use tracked shipping, and never send passwords or verification codes. Collector Vault does not guarantee users or trades.</span></section>
    <form className="trade-profile seller-panel" onSubmit={saveProfile}><div><span className="eyebrow">Matching profile</span><h2>How other traders see you</h2></div><label>Display name<input required minLength="2" maxLength="40" value={profile.display_name} onChange={e=>setProfile({...profile,display_name:e.target.value})} placeholder="Collector name"/></label><label className="toggle-row"><input type="checkbox" checked={profile.discoverable} onChange={e=>setProfile({...profile,discoverable:e.target.checked})}/><span>Let other members find me when our ISO/DISO and ready-to-trade lists match</span></label><button className="primary-button">Save preferences</button></form>
    <section className="trade-layout"><article className="seller-panel"><span className="eyebrow">Reciprocal matches</span><h2>{matches.length} possible trade{matches.length===1?'':'s'}</h2>{matches.map((m,i)=><div className="match-card" key={`${m.other_user_id}-${m.requested_figure_id}-${m.offered_figure_id}-${i}`}><strong>{m.display_name}</strong><p>You want <b>{m.requested_name}</b></p><p>They want <b>{m.offered_name}</b></p><button onClick={()=>start(m)}>Discuss this trade</button></div>)}{!profile.discoverable&&<p>Choose a display name and enable matching to see matches.</p>}{profile.discoverable&&!matches.length&&<p>No reciprocal matches yet. Keep your ISO/DISO and trade lists updated.</p>}</article>
      <article className="seller-panel"><span className="eyebrow">Inbox</span><h2>{threads.length} conversation{threads.length===1?'':'s'}</h2>{threads.map(t=><button className={`thread-card ${active?.id===t.id?'active':''}`} key={t.id} onClick={()=>openThread(t)}><strong>{t.requested?.name} ⇄ {t.offered?.name}</strong><small>{t.status} · {new Date(t.updated_at).toLocaleDateString()}</small></button>)}{!threads.length&&<p>Your trade conversations will appear here.</p>}</article>
      <article className="seller-panel chat-panel"><span className="eyebrow">Private conversation</span>{active?<><h2>{active.requested?.name} ⇄ {active.offered?.name}</h2><div className="message-list">{messages.map(m=><div className={`trade-message ${m.sender_id===userId?'mine':''}`} key={m.id}><p>{m.body}</p><small>{new Date(m.created_at).toLocaleString()}</small></div>)}{!messages.length&&<p>Introduce yourself and confirm the figure, condition, and shipping plan.</p>}</div><form className="message-form" onSubmit={send}><textarea maxLength="2000" value={body} onChange={e=>setBody(e.target.value)} placeholder="Write a message…" disabled={['closed','declined'].includes(active.status)}/><button className="primary-button" disabled={!body.trim()||['closed','declined'].includes(active.status)}>Send</button></form><div className="conversation-actions">{active.status==='pending'&&<button onClick={()=>updateStatus('active')}>Accept discussion</button>}<button onClick={()=>updateStatus('closed')}>Close</button><button onClick={report}>Report</button><button onClick={block}>Block</button></div></>:<div className="empty-panel"><h3>Select a conversation</h3><p>Messages about a proposed trade stay together here.</p></div>}</article>
    </section></main>
}
