import { useMemo, useState } from 'react'
import './LiveWheel.css'

const colors=['#f26b8a','#ffbd69','#7dcfb6','#7aa5ff','#c99bff','#ff8f70','#6fd0e8','#f6d365']
const clean=text=>text.split('\n').map(x=>x.trim()).filter(Boolean).slice(0,100)

export default function LiveWheel(){
 const [text,setText]=useState('Pink Rabbit\nFruit Robby\nSecret\nBlind Box\nFree Shipping\nBuyer’s Choice'),[rotation,setRotation]=useState(0),[spinning,setSpinning]=useState(false),[winner,setWinner]=useState(''),[history,setHistory]=useState([]),[removeWinner,setRemoveWinner]=useState(true)
 const entries=useMemo(()=>clean(text),[text]),gradient=entries.length?`conic-gradient(${entries.map((_,i)=>`${colors[i%colors.length]} ${i*360/entries.length}deg ${(i+1)*360/entries.length}deg`).join(',')})`:'#eadde2'
 function spin(){if(spinning||entries.length<2)return;const index=Math.floor(Math.random()*entries.length),slice=360/entries.length,target=360-(index*slice+slice/2),next=rotation+1800+((target-(rotation%360)+360)%360);setSpinning(true);setWinner('');setRotation(next);setTimeout(()=>{const selected=entries[index];setWinner(selected);setHistory(old=>[selected,...old].slice(0,12));setSpinning(false);if(removeWinner)setText(old=>clean(old).filter((_,i)=>i!==index).join('\n'))},4700)}
 function shuffle(){setText([...entries].sort(()=>Math.random()-.5).join('\n'));setWinner('')}
 return <section className="wheel-workspace"><article className="wheel-stage"><span className="eyebrow">Live-show game</span><h2>Collector Vault Wheel</h2><div className="wheel-wrap"><div className="wheel-pointer"/><div className="prize-wheel" style={{background:gradient,transform:`rotate(${rotation}deg)`}}>{entries.map((name,i)=><span key={`${name}-${i}`} style={{transform:`rotate(${i*360/entries.length+180/entries.length}deg)`}}><b>{name}</b></span>)}</div><button className="wheel-hub" onClick={spin} disabled={spinning||entries.length<2}>{spinning?'…':'SPIN'}</button></div><button className="spin-button" onClick={spin} disabled={spinning||entries.length<2}>{spinning?'Spinning…':'Spin the wheel'}</button>{winner&&<div className="winner-card"><small>Winner</small><strong>{winner}</strong></div>}</article><aside className="wheel-controls seller-panel"><span className="eyebrow">Wheel setup</span><h2>{entries.length} entries</h2><label>One entry per line<textarea value={text} onChange={e=>setText(e.target.value)} rows="12" placeholder="Add names, prizes, or products…"/></label><div className="wheel-buttons"><button onClick={shuffle}>Shuffle</button><button onClick={()=>{setText('');setWinner('')}}>Clear</button></div><label className="toggle-row"><input type="checkbox" checked={removeWinner} onChange={e=>setRemoveWinner(e.target.checked)}/><span>Remove winner after each spin</span></label><section className="winner-history"><h3>Winner history</h3>{history.map((name,i)=><div key={`${name}-${i}`}><b>{i+1}</b><span>{name}</span></div>)}{!history.length&&<p>Completed spins will appear here.</p>}</section></aside></section>
}
