import { useState } from 'react'
import { supabase } from '../lib/supabase'
import './OrdersDetailed.css'
const money=value=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(value||0)),today=new Date().toISOString().slice(0,10)
export default function OrdersDetailed({orders,suppliers,userId,reload,notify}){
 const blank={supplier_id:'',vendor_name:'',order_number:'',order_type:'case',description:'',order_date:today,status:'ordered',case_count:'',units_per_case:'',units:'',subtotal:'',shipping_cost:'',tax_amount:'',discount_amount:'',total_cost:'',payment_method:'',payment_status:'unpaid',paid_at:'',eta:'',carrier:'',tracking_number:'',received_at:'',notes:''},[form,setForm]=useState(blank)
 const set=(key,value)=>setForm(current=>({...current,[key]:value})),calculated=Math.max(0,Number(form.subtotal||0)+Number(form.shipping_cost||0)+Number(form.tax_amount||0)-Number(form.discount_amount||0))
 async function submit(e){e.preventDefault();const payload={...form,user_id:userId,supplier_id:form.supplier_id||null,total_cost:form.total_cost===''?calculated:Number(form.total_cost),eta:form.eta||null,paid_at:form.paid_at||null,received_at:form.received_at||null};['case_count','units_per_case','units','subtotal','shipping_cost','tax_amount','discount_amount'].forEach(key=>payload[key]=Number(payload[key]||0));const {error}=await supabase.from('seller_purchase_orders').insert(payload);notify(error?error.message:'Complete order saved.');if(!error){setForm(blank);reload()}}
 return <section className="order-entry-layout"><form className="seller-panel seller-form order-detail-form" onSubmit={submit}><div className="panel-heading"><div><span className="eyebrow">Complete order entry</span><h2>Log an order placed</h2></div><strong>{money(form.total_cost===''?calculated:form.total_cost)}</strong></div>
 <fieldset><legend>Vendor & order</legend><div className="form-row"><label>Saved supplier<select value={form.supplier_id} onChange={e=>set('supplier_id',e.target.value)}><option value="">Select supplier</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Vendor name<input value={form.vendor_name} onChange={e=>set('vendor_name',e.target.value)}/></label></div><div className="form-row"><label>PO / invoice #<input required value={form.order_number} onChange={e=>set('order_number',e.target.value)}/></label><label>Order type<select value={form.order_type} onChange={e=>set('order_type',e.target.value)}><option value="case">Figure case</option><option value="supply">Shipping supplies</option><option value="inventory">Loose inventory</option><option value="other">Other</option></select></label></div><label>Items / description<input required value={form.description} onChange={e=>set('description',e.target.value)} placeholder="Series, cases, boxes, mailers, labels…"/></label></fieldset>
 <fieldset><legend>Quantity</legend><div className="form-row three"><label>Cases<input type="number" min="0" value={form.case_count} onChange={e=>set('case_count',e.target.value)}/></label><label>Units per case<input type="number" min="0" value={form.units_per_case} onChange={e=>set('units_per_case',e.target.value)}/></label><label>Total units<input type="number" min="0" value={form.units} onChange={e=>set('units',e.target.value)} placeholder={String(Number(form.case_count||0)*Number(form.units_per_case||0)||0)}/></label></div></fieldset>
 <fieldset><legend>Costs</legend><div className="form-row"><label>Merchandise subtotal<input type="number" min="0" step=".01" value={form.subtotal} onChange={e=>set('subtotal',e.target.value)}/></label><label>Shipping / freight<input type="number" min="0" step=".01" value={form.shipping_cost} onChange={e=>set('shipping_cost',e.target.value)}/></label></div><div className="form-row"><label>Tax / duties<input type="number" min="0" step=".01" value={form.tax_amount} onChange={e=>set('tax_amount',e.target.value)}/></label><label>Discount<input type="number" min="0" step=".01" value={form.discount_amount} onChange={e=>set('discount_amount',e.target.value)}/></label></div><label>Final total <small>Calculated: {money(calculated)}</small><input type="number" min="0" step=".01" value={form.total_cost} onChange={e=>set('total_cost',e.target.value)} placeholder={calculated.toFixed(2)}/></label></fieldset>
 <fieldset><legend>Payment & status</legend><div className="form-row"><label>Payment method<select value={form.payment_method} onChange={e=>set('payment_method',e.target.value)}><option value="">Select method</option><option>Credit card</option><option>Bank transfer</option><option>PayPal</option><option>Cash</option><option>Terms / invoice</option><option>Other</option></select></label><label>Payment status<select value={form.payment_status} onChange={e=>set('payment_status',e.target.value)}><option value="unpaid">Unpaid</option><option value="deposit">Deposit paid</option><option value="paid">Paid</option><option value="refunded">Refunded</option></select></label></div><div className="form-row"><label>Order status<select value={form.status} onChange={e=>set('status',e.target.value)}><option value="draft">Draft</option><option value="ordered">Ordered</option><option value="confirmed">Confirmed</option><option value="shipped">Shipped</option><option value="received">Received</option><option value="cancelled">Cancelled</option></select></label><label>Paid date<input type="date" value={form.paid_at} onChange={e=>set('paid_at',e.target.value)}/></label></div></fieldset>
 <fieldset><legend>Dates & delivery</legend><div className="form-row three"><label>Order date<input type="date" value={form.order_date} onChange={e=>set('order_date',e.target.value)}/></label><label>Expected arrival<input type="date" value={form.eta} onChange={e=>set('eta',e.target.value)}/></label><label>Received date<input type="date" value={form.received_at} onChange={e=>set('received_at',e.target.value)}/></label></div><div className="form-row"><label>Carrier<input value={form.carrier} onChange={e=>set('carrier',e.target.value)} placeholder="UPS, FedEx, DHL…"/></label><label>Tracking number<input value={form.tracking_number} onChange={e=>set('tracking_number',e.target.value)}/></label></div><label>Notes<textarea value={form.notes} onChange={e=>set('notes',e.target.value)} placeholder="Terms, damages, shortages, backorders…"/></label></fieldset><button className="primary-button">Save complete order</button></form>
 <article className="seller-panel"><span className="eyebrow">Order book</span><h2>Placed orders</h2><div className="seller-table order-list">{orders.map(x=><div key={x.id}><span><strong>{x.supplier?.name||x.vendor_name||x.order_type}</strong><small>{x.order_number||'No PO'} · {x.description||`${x.units} units`}</small><small>{x.order_date}{x.eta?` → ETA ${x.eta}`:''}</small></span><span><b>{money(x.total_cost)}</b><small className="status">{x.status}</small><small>{x.payment_status}</small></span></div>)}{!orders.length&&<p>No orders logged yet.</p>}</div></article></section>
}
