-- Generated from the published Angel Vault historical guidebook catalog.
-- Official Sonny Angel announcement images remain preferred where already present.
begin;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Happy Little Bear','happy-little-bear-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/drink-collections/afternoon-tea-2023/04__happy-little-bear.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Afternoon Tea(2023)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Bumblebee','bumblebee-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/animal-collections/bug-s-world-2022/07__bumblebee.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Bug''s World (2022)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Bumblebee Robby Angel','bumblebee-robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/animal-collections/bug-s-world-2022/08__bumblebee-robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Bug''s World (2022)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Mexican Cactus','mexican-cactus-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/cactus-collections/cactus-series/05__mexican-cactus.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Cactus Series (2020)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Pink Rabbit','pink-rabbit-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/cactus-collections/cactus-series/06__pink-rabbit.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Cactus Series (2020)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Pink Monkey','pink-monkey-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/cactus-collections/cactus-series/07__pink-monkey.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Cactus Series (2020)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Pink Mouse','pink-mouse-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/cactus-collections/cactus-series/08__pink-mouse.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Cactus Series (2020)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Pink Parrot','pink-parrot-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/cactus-collections/cactus-series/09__pink-parrot.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Cactus Series (2020)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Cactus Robby Angel','cactus-robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/cactus-collections/cactus-series/10__cactus-robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Cactus Series (2020)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Happy Pink','happy-pink-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/special-collections/cat-life-2023/13__happy-pink.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Cat Life(2023)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Happy Pink Robby Angel','happy-pink-robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/special-collections/cat-life-2023/14__happy-pink-robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Cat Life(2023)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Mint Rabbit','mint-rabbit-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/sweets-collections/charm-candy-store-2023/06__mint-rabbit.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Charm Candy Store(2023)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Cherry','cherry-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/cherry-blossom-collections/cherry-blossom-night-version-2021/05__cherry.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Cherry Blossom -Night Version- (2021)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Cherry Robby Angel','cherry-robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/cherry-blossom-collections/cherry-blossom-night-version-2021/06__cherry-robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Cherry Blossom -Night Version- (2021)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Cherry','cherry-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/cherry-blossom-collections/cherry-blossom-peaceful-spring-edition-2022/05__cherry.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Cherry Blossom -Peaceful Spring Edition- (2022)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Cherry Robby Angel','cherry-robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/cherry-blossom-collections/cherry-blossom-peaceful-spring-edition-2022/06__cherry-robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Cherry Blossom -Peaceful Spring Edition- (2022)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Cherry','cherry-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/cherry-blossom-collections/cherry-blossom-series/05__cherry.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Cherry Blossom Series' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Cherry Robby Angel','cherry-robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/cherry-blossom-collections/cherry-blossom-series/06__cherry-robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Cherry Blossom Series' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Silk Hat Rabbit','silk-hat-rabbit-secret','secret',950,true,'https://angelvaulttracker.com/app/app/assets/manual/user-photo-candidates/circus-series/silk-hat-rabbit-candidate.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Circus Series' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Clown Robby Angel','clown-robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/circus-collections/circus-series/08__clown-robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Circus Series' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Santa''s Helper Mouse','santa-s-helper-mouse-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/christmas-collections/dreaming-christmas-2021/07__santa-s-helper-mouse.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Dreaming Christmas (2021)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Santa''s Helper Robby Angel','santa-s-helper-robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/christmas-collections/dreaming-christmas-2021/08__santa-s-helper-robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Dreaming Christmas (2021)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Rainbow Sunflower Lion Robby Angel','rainbow-sunflower-lion-robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/flower-collections/flower-gift-2023/07__rainbow-sunflower-lion-robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Flower Gift(2023)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Robby Angel','robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/regulars/flower-collections/flower-series/14__robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Flower Series' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Love Lop Ear Rabbit','love-lop-ear-rabbit-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/valentines-collections/gifts-of-love-2024/09__love-lop-ear-rabbit.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Gifts of Love(2024)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Love Red Rabbit','love-red-rabbit-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/valentines-collections/gifts-of-love-2024/07__love-red-rabbit.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Gifts of Love(2024)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Love Pink Rabbit','love-pink-rabbit-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/valentines-collections/gifts-of-love-2024/08__love-pink-rabbit.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Gifts of Love(2024)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Chocolate Robby Angel','chocolate-robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/valentines-collections/gifts-of-love-2024/10__chocolate-robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Gifts of Love(2024)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Rabbit Pumpkin (Orange)','rabbit-pumpkin-orange-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/special-collections/halloween-series-2021-additional-secret/07__rabbit-pumpkin-orange.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Halloween Series(2021)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Pumpkin Pants Robby Angel (Orange)','pumpkin-pants-robby-angel-orange-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/special-collections/halloween-series-2021-additional-secret/10__pumpkin-pants-robby-angel-orange.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Halloween Series(2021)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Rabbit Pumpkin (Purple)','rabbit-pumpkin-purple-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/special-collections/halloween-series-2021-additional-secret/08__rabbit-pumpkin-purple.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Halloween Series(2021)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Rabbit Pumpkin (Green)','rabbit-pumpkin-green-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/special-collections/halloween-series-2021-additional-secret/09__rabbit-pumpkin-green.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Halloween Series(2021)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Pumpkin Pants Robby Angel (Purple)','pumpkin-pants-robby-angel-purple-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/special-collections/halloween-series-2021-additional-secret/11__pumpkin-pants-robby-angel-purple.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Halloween Series(2021)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Pumpkin Pants Robby Angel (Green)','pumpkin-pants-robby-angel-green-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/special-collections/halloween-series-2021-additional-secret/12__pumpkin-pants-robby-angel-green.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Halloween Series(2021)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Pumpkin Pants Robby Angel (Pink)','pumpkin-pants-robby-angel-pink-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/special-collections/halloween-series-2021-additional-secret/13__pumpkin-pants-robby-angel-pink.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Halloween Series(2021)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Golden Lucky Cat','golden-lucky-cat-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/special-collections/japanese-good-luck-2021/07__golden-lucky-cat.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Japanese Good Luck(2021)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Daruma Robby Angel','daruma-robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/special-collections/japanese-good-luck-2021/08__daruma-robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Japanese Good Luck(2021)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Robby Angel','robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/regulars/marine-collections/marine-series/14__robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Marine Series' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Unicorn','unicorn-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/valentines-collections/message-of-love-2022/07__unicorn.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Message of Love (2022)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Kiss me Robby Angel','kiss-me-robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/valentines-collections/message-of-love-2022/08__kiss-me-robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Message of Love (2022)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'NY Bull','ny-bull-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/special-collections/newyork-series/06__ny-bull.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='NewYork Series' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Big Apple Robby Angel','big-apple-robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/special-collections/newyork-series/05__big-apple-robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='NewYork Series' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Pineapple Swimmer','pineapple-swimmer-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/special-collections/okinawa-series/07__pineapple-swimmer.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Okinawa Series' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Pineapple Robby Angel','pineapple-robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/special-collections/okinawa-series/08__pineapple-robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Okinawa Series' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Seoul Strawberry Robby Angel','seoul-strawberry-robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/other-collections/sonny-angel-terrace-seoul-limited-stuffed/01__seoul-strawberry-robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Seoul Series' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Pink Bear','pink-bear-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/christmas-collections/sonny-angel-christmas-ornament-2022/07__pink-bear.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Sonny Angel Christmas Ornament(2022)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Blue Bear','blue-bear-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/christmas-collections/sonny-angel-christmas-ornament-2022/08__blue-bear.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Sonny Angel Christmas Ornament(2022)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Rabbit','rabbit-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/christmas-collections/sonny-angel-christmas-ornament-2023/05__rabbit.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Sonny Angel Christmas Ornament(2022)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Ornament Robby Angel','ornament-robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/christmas-collections/sonny-angel-christmas-ornament-2022/10__ornament-robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Sonny Angel Christmas Ornament(2022)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Friendship Work With Robby Angel','friendship-work-with-robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/special-collections/sonny-angel-enjoy-the-moment-2022/07__friendship-work-with-robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Sonny Angel Enjoy the Moment (2022)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Jeju Surfer','jeju-surfer-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/special-collections/sonny-angel-hello-jeju-2022/07__jeju-surfer.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Sonny Angel Hello Jeju (2022)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Dol Hareubang Robby Angel','dol-hareubang-robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/special-collections/sonny-angel-hello-jeju-2022/08__dol-hareubang-robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Sonny Angel Hello Jeju (2022)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'UFO','ufo-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/special-collections/sonny-angel-in-space-adventure-series-2020/07__ufo.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Sonny Angel in Space Adventure Series (2020)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Alien Robby Angel','alien-robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/special-collections/sonny-angel-in-space-adventure-series-2020/08__alien-robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Sonny Angel in Space Adventure Series (2020)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Humpty Dumpty','humpty-dumpty-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/special-collections/sonny-angel-in-wonderland-series-2020/07__humpty-dumpty.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Sonny Angel in Wonderland Series (2020)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Drink me Robby Angel','drink-me-robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/special-collections/sonny-angel-in-wonderland-series-2020/08__drink-me-robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Sonny Angel in Wonderland Series (2020)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Robby Angel','robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/regulars/sweets-collections/sweets-series/14__robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Sweets Series' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Chipmunk','chipmunk-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/special-collections/the-sonny-angel-town-musicians-2021/07__chipmunk.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='The Sonny Angel Town Musicians(2021)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Color Guard Robby Angel','color-guard-robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/special-collections/the-sonny-angel-town-musicians-2021/08__color-guard-robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='The Sonny Angel Town Musicians(2021)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Chocolate Toy Poodle','chocolate-toy-poodle-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/valentines-collections/valentine-series-2020/05__chocolate-toy-poodle.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Valentine Series (2020)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Chocolate Robby Angel','chocolate-robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/valentines-collections/gifts-of-love-2024/10__chocolate-robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Valentine Series (2020)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Chocolate Rabbit','chocolate-rabbit-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/valentines-collections/valentine-s-day-series-2019/02__chocolate-rabbit.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Valentine''s Day Series (2019)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Chocolate Robby Angel','chocolate-robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/valentines-collections/gifts-of-love-2024/10__chocolate-robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Valentine''s Day Series (2019)' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Teddy Bear','teddy-bear-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/valentines-collections/valentine-s-day-series-2017/02__teddy-bear.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Valentine''s Day Series 2017' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Sweet Kitty','sweet-kitty-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/valentines-collections/valentine-s-day-series-2017/04__sweet-kitty.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Valentine''s Day Series 2017' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Plushie Angel Robby Angel','plushie-angel-robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/valentines-collections/valentine-s-day-series-2017/05__plushie-angel-robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Valentine''s Day Series 2017' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Single Rose','single-rose-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/valentines-collections/valentine-s-day-series-2018/01__single-rose.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Valentine''s Day Series 2018' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Rose Bouquet','rose-bouquet-secret','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/valentines-collections/valentine-s-day-series-2018/02__rose-bouquet.png','https://angelvaulttracker.com/',now(),'secret','historical_guidebook',array[]::text[]
from public.series s where s.name='Valentine''s Day Series 2018' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Rose Robby Angel','rose-robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/limited/valentines-collections/valentine-s-day-series-2018/05__rose-robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Valentine''s Day Series 2018' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
insert into public.figures (series_id,name,slug,rarity,sort_order,active,image_url,image_source_url,image_verified_at,edition_type,verification_source,aliases)
select s.id,'Robby Angel','robby-angel-robby','secret',950,true,'https://angelvaulttracker.com/app/sonny_png_library/regulars/vegetable-collections/vegetable-series/14__robby-angel.png','https://angelvaulttracker.com/',now(),'robby','historical_guidebook',array[]::text[]
from public.series s where s.name='Vegetable Series' and s.active=true order by s.id limit 1
on conflict (series_id,slug) do update set name=excluded.name,rarity=excluded.rarity,active=true,image_url=excluded.image_url,image_source_url=excluded.image_source_url,image_verified_at=excluded.image_verified_at,edition_type=excluded.edition_type,verification_source=excluded.verification_source;
commit;
